name: Proxy Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"

jobs:
  scanner:
    runs-on: ubuntu-latest
    concurrency:
      group: proxy-scan
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - name: Start Scan
        run: |
          bun install && bun run ./helper/proxyip.ts

      - name: Publish Result
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Update proxyip [skip ci]"
            git push origin main --force
          else
            echo "Tidak ada perubahan data, melewati tahap commit."
          fi
